### ISSUE TITLE
Support scss filetype

### ISSUE THREAD

**Issue by razor-x** [gcorne/vim-sass-lint#1]
As a basic test, I did this by duplicating the code but changing sass to scss: https://github.com/rxfork/vim-sass-lint/commit/383fb4888934ec57866d4dcd054fcfb55c7cdd13

Maybe there is a simple way to add scss support without code duplication?

**Comment by gcorne** [comment]
> Maybe there is a simple way to add scss support without code duplication?

Yeah, we can use a redirect as I did in 9c2c16f.
